replicaCount: 2
openmetadata:
  config:
    smtpConfig:
      enableSmtpServer: true
      emailingEntity: "OpenMetadata"
      supportUrl: "https://slack.open-metadata.org"
      transportationStrategy: "SMTP_TLS"
      openMetadataUrl: "https://metadata.bilthouse-data.com"
      serverEndpoint: "smtp.office365.com"
      serverPort: "587"
      senderMail: 
      username: 
      password: 
        secretRef: "smtp-secret"
        secretKey: "password"

    database:
      #host: postgresql
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata_db
      auth:
        #username: 
        password:
          secretRef: postgresql-secret
          secretKey: postgresql-password
    pipelineServiceClientConfig:
      apiEndpoint: http://openmetadata-dependencies-web.openmetadata.svc.cluster.local:8080
      metadataApiEndpoint: http://openmetadata.openmetadata.svc.cluster.local:8585/api
    authentication:
      enableSelfSignup: false   # dont allow users to signup from home page

image:
  tag: 1.3.0
nodeSelector:
  prodpool: activepool
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/ssl-redirect: "true" # redirects http traffic to https route
  hosts:
    - host: metadata.bilthouse-data.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: openmetadata-tls
      hosts:
        - metadata.bilthouse-data.com

