replicaCount: 2

openmetadata:
  config:
    smtpConfig:
      enableSmtpServer: true
      emailingEntity: "OpenMetadata"
      supportUrl: "https://slack.open-metadata.org"
      transportationStrategy: "SMTP_TLS"
      openMetadataUrl: "https://metadata.bilthouse-data.com"
      serverEndpoint: "smtp.office365.com"
      serverPort: "587"
      senderMail: 
      username: dwh@bilthouse.com
      password: 
        secretRef: "smtp-secret"
        secretKey: "password"

    authorizer:
      className: "org.openmetadata.service.security.DefaultAuthorizer"
      containerRequestFilter: "org.openmetadata.service.security.JwtFilter"
      initialAdmins:
        - "admin"
        - "d.marimuthu@bilthouse.com"
      principalDomain: "open-metadata.org"
    authentication:
      provider: "azure"
      publicKeys:
      - "https://metadata.bilthouse-data.com/api/v1/config/jwks" # Make sure this "/api/v1/config/jwks" is always configured to enable JWT tokens
      - "https://login.microsoftonline.com/common/discovery/keys"
      authority: "https://login.microsoftonline.com/{get-it-from-onepassword}"
      clientId: "get-it-from-onepassword" # Azure Application
      callbackUrl: "https://metadata.bilthouse-data.com//callback"
      enableSelfSignup: false   # dont allow users to signup from home page

    database:
      host: pg-dw-production.postgres.database.azure.com
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata_db
      auth:
        username: bilthouse
        password:
          secretRef: postgresql-secret
          secretKey: postgresql-password
    pipelineServiceClientConfig:
      apiEndpoint: http://openmetadata-dependencies-web.openmetadata.svc.cluster.local:8080
      metadataApiEndpoint: http://openmetadata.openmetadata.svc.cluster.local:8585/api
 
image:
  tag: 1.3.0
nodeSelector:
  metapool: activepool
# affinity:
#   #do not co locate pods on same node
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: app.kubernetes.io/name
#           operator: In
#           values:
#           - openmetadata
#       topologyKey: "kubernetes.io/hostname"
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/ssl-redirect: "true" # redirects http traffic to https route
  hosts:
    - host: metadata.bilthouse-data.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: openmetadata-tls
      hosts:
        - metadata.bilthouse-data.com

