#using the values.yaml file to override the default values in the default helm chart
global:
  pipelineServiceClientConfig:
    apiEndpoint: http://openmetadata-dependencies-web.openmetadata.svc.cluster.local:8080
    metadataApiEndpoint: http://openmetadata.openmetadata.svc.cluster.local:8585/api

replicaCount: 2
openmetadata:
  config:
    database:
      #host: postgresql
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata_db
      auth:
        #username: 
        password:
          secretRef: postgresql-secret
          secretKey: postgresql-password

    authentication:
      enableSelfSignup: false   # dont allow users to signup from home page

image:
  tag: 1.3.0
nodeSelector:
  agentpool: usernodepool
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/ssl-redirect: "true" # redirects http traffic to https route
  hosts:
    - host: metadata.bilthouse-data.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: openmetadata-tls
      hosts:
        - metadata.bilthouse-data.com

